### PR TITLE
fix header value array in api and add soft purge option

### PR DESCRIPTION
**Pull request by 22ca54d00f05391d6ffee4bc23a5ba60**
The Fastly-Key header was being set like this when I was testing:

0: Fastly-Key: key value

wp_remote_request's header array seems to be an associative array of key => value 

Also added soft-purge option to advanced tab to set soft purge header

### CODE REVIEW

**Comment by aspires** [comment]
@vvuksan I don't see any issues here, but can you take a look to confirm?

**Comment by rdebeasi** [comment]
@vvuksan Any updates on this pull request? We've applied the patch ourselves and are using it in production. It works well, but I'd love to be able to get back onto the mainline version of the Fastly plugin.

**Comment by simonwistow** [comment]
This should now be merged into master.

Apologies for not doing this far, far sooner.

**Comment by rdebeasi** [comment]
Awesome news - thank you!!!!

**Pull request closed without merging**
